name: remap_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bcftools=1.22
  - bio=1.8.1
  - biopython=1.86
  - cigar=0.1.3
  - hifiasm=0.25.0
  - minimap2=2.28
  - numba=0.62.1
  - numpy=2.2.6
  - pandas=2.3.3
  - pip=25.2
  - pysam=0.23.3
  - python=3.10.0
  - samtools=1.22.1
  - wheel=0.45.1
  - pip:
      - vacmap-index==0.0.2
      - setuptools==63.0.0

